### PR TITLE
Fix broken url and minor improvements

### PR DESCRIPTION
**Pull request by vmx-kbabenko**
- Reduce layering in Dockerfile
 - Changing default download URL for OVPN configs since old one is dead
 - Add error reporting for dead URL
 - Since OVPN config file names use snake case, try to convert entries like "US West" into "us_west" for compatibility

### CODE REVIEW

**Review by act28 — CHANGES_REQUESTED** [review]
Can you also please add a test to check that the `$REGION.ovpn` file exists? Apparently, `US East` was missing from the previous zip.

**Comment by act28** [comment]
Thanks for catching this. 👍 Apart from that small change, LGTM.

**Comment by vmx-kbabenko** [comment]
Added the requested check.

**Review by act28 — APPROVED** [review]
LGTM.

**Pull request merged**
